import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import "./globals.css";
import StoreProvider from "./components/StoreProvider";
import ThemeProvider from "./components/ThemeProvider";
import QueryProvider from "./components/QueryProvider";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <StoreProvider>
          <QueryProvider>
            <ThemeProvider>
              <ToastContainer limit={3} autoClose={3000} />
              <AppRouterCacheProvider options={{ enableCssLayer: true }}>
                {children}
                <SpeedInsights />
              </AppRouterCacheProvider>
            </ThemeProvider>
          </QueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}

export default RootLayout;
